POST http://localhost:3000/itens
Content-Type: application/json

{
    "Produto": "Produto 02",
    "Preco": "1600.99",
    "Unidade": 15
}

###
GET http://localhost:3000/itens?search=

###
PUT http://localhost:3000/itens/031377d5-399c-4eea-a519-e4d212ee234b
Content-Type: application/json

{
    "Produto": "Produto 02",
    "Preco": "1600.99",
    "Unidade": 10
}

###
DELETE http://localhost:3000/itens/e5b2434b-9704-48c0-a10d-949d437d8f5a