### Listar todos os acessórios ou filtrar por pesquisa
GET http://localhost:3000/acessorios?search=
Content-Type: application/json

### Criar múltiplos acessórios (20 inserções)

### Criar Fone Bluetooth TWS
POST http://localhost:3000/acessorios
Content-Type: application/json

{
  "nome": "Fone Bluetooth TWS",
  "tipo": "fone",
  "marca": "SoundCore",
  "compatibilidade": ["todos"],
  "imagemUrl": "https://example.com/fone-tws.jpg",
  "material": "plástico",
  "cores_disponiveis": ["branco", "preto"],
  "preco": 199.90,
  "estoque": 30,
  "garantia_meses": 6
}


### Atualizar um acessório existente
PUT http://localhost:3000/acessorios/031377d5-399c-4eea-a519-e4d212ee234b
Content-Type: application/json

{
    "nome": "Capa Protetora iPhone 14",
    "tipo": "capa",
    "marca": "CaseMate Premium",
    "compatibilidade": ["iPhone 14", "iPhone 14 Pro"],
    "imagemUrl": "https://example.com/capa-iphone14-premium.jpg",
    "material": "silicone",
    "cores_disponiveis": ["preto", "azul", "rosa", "verde"],
    "preco": 99.90,
    "estoque": 40,
    "garantia_meses": 12
}

### Deletar um acessório
DELETE http://localhost:3000/acessorios/df606ebe-9d2d-434d-8907-f06e0ec517ba