### Criar novo pedido
POST http://localhost:3000/pedidos
Content-Type: application/json

{
    "usuario_id": "595a107c-b797-4a31-96c5-7b662badc251",
    "forma_pagamento": "cartao",
    "itens": [
        {"produto_id": "2abea576-ffb5-4a69-b8f5-b206aa1f6dae", "quantidade": 2, "preco_unitario": 10.50},
        {"produto_id": "3cdf20ea-c84e-473c-838e-4d5762fb5c5d", "quantidade": 1, "preco_unitario": 25.99}
    ]
}

### Listar todos os pedidos de um usuário
GET http://localhost:3000/pedidos?usuario_id=595a107c-b797-4a31-96c5-7b662badc251

### Listar pedidos por status
GET http://localhost:3000/pedidos?usuario_id=595a107c-b797-4a31-96c5-7b662badc251&status=pendente

### Buscar pedido específico
GET http://localhost:3000/pedidos/cfbd0f46-9fe9-4d0d-891f-d0261dea6c0e

### Atualizar status do pedido
PATCH http://localhost:3000/pedidos/cfbd0f46-9fe9-4d0d-891f-d0261dea6c0e/status
Content-Type: application/json

{
    "status": "concluido"
}

### Cancelar pedido
PATCH http://localhost:3000/pedidos/3fa85f64-5717-4562-b3fc-2c963f66afa6/cancelar

### Deletar pedido
DELETE http://localhost:3000/pedidos/3466433a-483c-4dab-87ce-6f3ac5efb9db