POST http://localhost:3000/itens
Content-Type: application/json

{
    "Produto": "Produto 01",
    "Preco": "1600.99",
    "Unidade": 15
}

###
GET http://localhost:3000/itens?search=1

###
PUT http://localhost:3000/itens/ea8f8d05-6192-41bb-bdde-a42804709c44
Content-Type: application/json

{
    "Produto": "Produto 09",
    "Preco": "1600.99",
    "Unidade": 15
}

###
DELETE http://localhost:3000/itens/94487d88-37b8-4efa-b422-66b99bb960da